title: Buffer Afterthought
author: Joao Pedro Nascimento Monteiro
email: joaonasmont@gmail.com
description: >
  A technical devlog covering systems, engineering, security, and IoT. Join this humble Bit Plumber as I document my projects, break things, get frustrated, eventually (hopefully) ship something and share what I learn along the way!

# 1. URL must be lowercase for GitHub Pages to link CSS correctly
url: "https://joaonasmonteiro.github.io"
baseurl: ""

# 2. Theme Settings
theme: "minima"
permalink: /blog/:title/

# 3. Build Settings
markdown: kramdown
kramdown:
  math_engine: mathjax 

collections:
  projects:
    output: true  
    permalink: /projects/:path/

contact_links:
  - title: Email
    url: "mailto:joaonasmont@gmail.com"
    icon: "fas fa-envelope"  # Icon code from FontAwesome

  - title: LinkedIn
    url: "https://www.linkedin.com/in/joaonasmonteiro/"
    icon: "fab fa-linkedin"

  - title: GitHub
    url: "https://github.com/JoaoNasMont"
    icon: "fab fa-github"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache