title: Buffer Overthought
author: Joao Pedro Nascimento Monteiro
email: joaonasmont@gmail.com
description: >
  A technical devlog covering systems, engineering, security, and IoT. Join this humble Silicon Wrangler and bit Plumber as I document my projects, break things, get frustrated, eventually ship something and share what I learn along the way!  

theme: minima

baseurl: "" 
url: "https://yourusername.github.io"
permalink: /blog/:title/

github_username: JoaoNasMont

markdown: kramdown
kramdown:
  input: GFM  
  math_engine: mathjax 
syntax_highlighter: none

#header_pages:
  #- about.md
  #- projects.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
