title: Buffer Overthought
author: Joao Pedro Nascimento Monteiro
email: joaonasmont@gmail.com
description: >
  A technical devlog covering systems, engineering, security, and IoT. Join this humble Silicon Wrangler and bit Plumber as I document my projects, break things, get frustrated, eventually ship something and share what I learn along the way!  

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
