title: Buffer Overthought
author: Joao Pedro Nascimento Monteiro
email: joaonasmont@gmail.com
description: >
  A technical devlog covering systems, engineering, security, and IoT.

# 1. URL must be lowercase for GitHub Pages to link CSS correctly
url: "https://joaonasmonteiro.github.io"
baseurl: ""

# 2. Theme Settings
theme: "minima"
permalink: /blog/:title/

# 3. Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache