title: Buffer Afterthought
author: Joao Pedro Nascimento Monteiro
email: joaonasmont@gmail.com
description: >
  A technical devlog covering systems, engineering, security, and IoT. Join this humble dev as I document my projects, break things, get frustrated, eventually (hopefully) ship something and share what I learn along the way!

# 1. URL must be lowercase for GitHub Pages to link CSS correctly
url: "https://joaonasmonteiro.github.io"
baseurl: ""

# 2. Theme Settings
theme: "minima"
permalink: /blog/:title/

# 3. Build Settings
markdown: kramdown
kramdown:
  math_engine: mathjax 

collections:
  projects:
    output: true  
    permalink: /projects/:path/

github_username: JoaoNasMont


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache